# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: Inria-AIO, Cryspen, and Christian Amsüss

[package]
name = "embedded-cal-libcrux"
description = "Software implementation of embedded-cal based on libcrux"

edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
version.workspace = true

[features]
# The check-secret-independence feature can be used as a lightweight check that secrets are not used
# in a way that depends on their values. This is achieved with the https://docs.rs/libcrux-secrets crate
# which provides type-aliases that either point to the normal rust integers, or to specially restricted
# new-types if the feature is enabled. This feature should only be activated locally or in CI to check
# for secret independence, and not when depending on the embedded-cal-libcrux crate.
check-secret-independence = ["libcrux-secrets/check-secret-independence", "libcrux-iot-sha3/check-secret-independence"]

## Enables the `Extender::standalone()` constructor.
standalone = ["embedded-cal-rand"]

[dependencies]
embedded-cal.workspace = true
libcrux-iot-aes = "0.0.1-alpha.1"
libcrux-iot-sha3 = "0.0.1-alpha.1"
libcrux-iot-p256 = { version = "0.0.1-alpha.1", features = ["expose-hacl"] }
libcrux-secrets = "0.0.6"
libcrux-sha2 = "0.0.8"
libcrux-traits = "0.0.8"

rand_core.workspace = true

embedded-cal-rand = { workspace = true, features = ["new_from_sys"], optional = true }

[dev-dependencies]
testvectors.path = "../testvectors"
embedded-cal-rand = { path = "../embedded-cal-rand", features = ["new_from_sys"] }

[package.metadata.docs.rs]
all-features = true
