# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: Inria-AIO, Cryspen, and Christian Amsüss

[package]
name = "embedded-cal-rustcrypto"
description = "Software implementation of embedded-cal based on RustCrypto libraries"
documentation = "https://docs.rs/embedded-cal-rustcrypto/"

edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
version.workspace = true

[dependencies]
aes = { version = "0.9.3", default-features = false }
ccm = { version = "0.6.1", default-features = false }
digest = "0.11.3"
embedded-cal.workspace = true
heapless = { version = "0.9.3", features = ["zeroize"] }
hmac = { version = "0.13.0", default-features = false }
p256 = { version = "0.14.0", default-features = false, features = ["ecdh"] }
sha2 = { version = "0.11.0", default-features = false }
zeroize = { version = "1.8.2", default-features = false }

generic-array = "1.4.0"

rand_core.workspace = true
x25519-dalek = { version = "3.0.0", default-features = false, features = ["static_secrets", "zeroize"] }

embedded-cal-rand = { workspace = true, features = ["new_from_sys"], optional = true }

[dev-dependencies]
embedded-cal-rand = { workspace = true, features = ["new_from_sys"] }
testvectors.path = "../testvectors"

[features]
## Enables the use of the system allocator for AEAD algorithms.
##
## In particular, this is needed because the rustcrypto AEAD mechanism expects
## the AAD to be provided in contiguous memory, whereas the embedded-cal way is
## to allow feeding them piecemeal (e.g. to accommodate OSCORE's Class I items,
## whose size is only bounded by a full message size).
##
## When this feature is not active, a fixed size (currently 1024 byte) buffer
## is allocated inside the `Cal` instance, and exceeding that size is treated
## similar to a memory allocation failure, resulting in a panic.
alloc = []

## Enables the `Standalone::standalone()` constructor.
standalone = ["embedded-cal-rand"]

[package.metadata.docs.rs]
all-features = true
