# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: Inria-AIO, Cryspen, and Christian Amsüss

[package]
name = "embedded-cal-rand"
description = "Making a cryptographically secure random number generator accessible in embedded-cal"
documentation = "https://docs.rs/embedded-cal-rand/"

edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
version.workspace = true

[dependencies]
embedded-cal.workspace = true

rand_core.workspace = true

rand = {version = "0.10", optional = true, features = ["std_rng", "sys_rng"], default-features = false }

[features]
## Enables the [`WithRng::new_with_sys()`] constructor.
new_from_sys = ["dep:rand"]

[package.metadata.docs.rs]
all-features = true
