# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: Inria-AIO, Cryspen, and Christian Amsüss

[package]
name = "embedded-cal-software-demo"
description = "Software implementation of embedded-cal for tests, research and illustration"
documentation = "https://docs.rs/embedded-cal-software-demo/"

edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
version.workspace = true

[dependencies]
embedded-cal.workspace = true
rand_core.workspace = true

[dev-dependencies]
embedded-cal-testvectors.path = "../embedded-cal-testvectors"
